devops-coop/ansible-haproxy

meta/main.yml

```
- executing: git clone https://github.com/FloeDesignTechnologies/ansible-haproxy ansible-haproxy
- executing: git archive --prefix=ansible-haproxy/ --output=/var/folders/40/1_7mkdwj20gdf3133bdhrwgm0000gn/T/tmpTp1ddK.tar HEAD
- extracting ansible-haproxy to /usr/local/etc/ansible/roles/ansible-haproxy
---
- ansible-haproxy was installed successfully
Traceback (most recent call last):
File "/usr/local/Cellar/ansible/1.8.3/libexec/bin/ansible-galaxy", line 954, in <module>
main()
File "/usr/local/Cellar/ansible/1.8.3/libexec/bin/ansible-galaxy", line 948, in main
fn(args, options, parser)
File "/usr/local/Cellar/ansible/1.8.3/libexec/bin/ansible-galaxy", line 842, in execute_install
role_dependencies = role_data['dependencies']
KeyError: 'dependencies'
```
Was getting the above when …

Fixed ansible galaxy dependencies error

---

meta/main.yml
tasks/main.yml
templates/defaults.cfg

Putting logs in /etc/ even error logs does not really conform to any standard. If users with to set this they can do so later.
Checked for existence of EPEL repo first as automatically inserting an epel repo based apon file could break implementation into some environments where repos are silo-ed into one file.

Made changes to improve compatibility with CentOS operating systems.

---

tasks/main.yml
templates/userlist.cfg

This commit allows adding userlists if [both formats](http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#3.4) via ansible.
Example vars:
```
haproxy_userlists:
- name: 'MyList'
users: 
- name: 'user1'
password: 'insecure-password user1'
- name: 'user2'
password: 'insecure-password user2'
```

Add support for userlists

---

templates/backend.cfg

According to HAProxy 1.5 documentation the directive to make the health check look for specific content in the response is `http-check expect` not `http-check except`.
http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#4-http-check%20expect

Fix http-check expect

---

tasks/main.yml

Hi, I get the following error when running the module on CentOS 7 
`TASK: [info.haproxy | Check epel repo] ****************************************
failed: [192.168.0.10] => {"changed": true, "cmd": ["yum", "repolist", "|", "grep", "-qi", "EPEL"], "delta": "0:00:00.093096", "end": "2015-03-25 01:21:43.802234", "rc": 1, "start": "2015-03-25 01:21:43.709138", "warnings": ["Consider using yum module rather than running yum"]}
stderr: Command line error: no such option: -i
`
According to http://docs.ansible.com/command_module.html the `|` operator is not supported in the `command` module and the `shell` module should be used instead. 
Changing `command` to `shell` seems to fix this error on CentOS 7.

Updated check epel task

---

templates/frontend.cfg
templates/listen.cfg
vars/main.yml

Added new variables in order to setup the frontend and listen
with ssl (native support now in haproxy 1.5).
Note the pem format for the cert file.
Also included in the sample file, an example of ciphers that
can be chosen as well.

added ssl support for frontend and listen

---

templates/frontend.cfg
vars/main.yml

This allows the use of the ['http-request'](http://cbonte.github.io/haproxy-dconv/configuration-1.5.html#http-request) option for frontends, eg.:
```
---
haproxy_frontends:
- name: "http-in"
bind:
- "{{ ansible_eth0.ipv4.address }}:80"
default-backend: 'public-http'
acl:
- name: 'Users-auth-ok'
condition: 'http_auth(users)'
http_request:
- action: allow
condition: 'if Users-auth-ok'
- action: 'auth'
param: 'realm "My secret server"'
condition: 'if !Users-auth-ok'
- action: 'deny'
```

Add http-request option to frontends

---

templates/backend.cfg
templates/frontend.cfg
templates/listen.cfg
vars/main.yml

Up to now, only the default section could be used to set
timeouts. This adds support for timeouts in listen, frontend
and backend sections.
Note that all timeout parameters do not apply to all sections
but will not be checked for sanity by this playbook.

added timeout settings for listen, frontend and backend

---

templates/frontend.cfg

Without those fixes some extraneous indentation could be inserted either in directives after  the`acl`  directives block, or for each `use_backend` directive.

Fix some whitespace issues in frontends template

---

templates/global.cfg
vars/main.yml

example usage:
```
ssl_default_bind_options: no-sslv3 no-tls-tickets
ssl_default_bind_ciphers: EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+ECDSA+SHA256:EECDH+aRSA+SHA384:EECDH+aRSA+SHA256:EECDH:EDH+aRSA:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!RC4
```

add another two missing global settings

---

templates/listen.cfg
vars/main.yml

enable the creation of a dedicated stats-page as follows:
```
haproxy_listen:
- name: stats
bind:
- ':8888'
description: stats for site
stats:
enabled: true
uri: /
realm: Haproxy\ Stats
auth: admin:secret
refresh: 5s
```

allow to access the  stats page on a dedicated ip and/or port

---

filter_plugins/flatten.py
templates/global.cfg
vars/main.yml

This commit adds support for setting `tune.chksize` and other parameters in `haproxy_global`.
Partially addresses #49.

Support global `tune` parameters

---

tasks/install.yml

This commit extends the backports repository task to support Debian 6
"squeeze" and 8 "jessie".
It is backwards-compatible with the previous task which only supported
Debian 7 "wheezy".
**Duplicate of #37, moved to this repository as a feature branch.**

Add backports support for Debian squeeze/jessie

---

defaults/main.yml
templates/global.cfg

Hello !
I was using this role and my fix before the change of maintainers. 
I decided to switch on the original fork with new maintainers.
In this PR, 3 commits : 
2 for closing issues #83  and #84 
1 for ability to have a good rating on ssllabs checkings. Maybe your prefer to switch this configuration in the vars/main.yml example ? 
Let me know ;)

Improve [global] ssl configuration. Provide default ssl configuration for 'A' rating in ssllabs checks

---

tasks/install.yml

stops this error when ansible is run with the `--check` command
```
fatal: [x.x.x.x]: FAILED! => {"failed": true, "msg": "The conditional check 'ansible_pkg_mgr == \"yum\" and
epel_repo_check is defined and epel_repo_check.rc != 0' failed. The error was: error while evaluating 
conditional (ansible_pkg_mgr == \"yum\" and epel_repo_check is defined and epel_repo_check.rc != 0):
'dict object' has no attribute 'rc'\n\nThe error appears to have been in '/usr/local/etc/ansible/roles/devops-
coop.haproxy/tasks/install.yml': line 14, column 3, but may\nbe elsewhere in the file depending on the exact
syntax problem.\n\nThe offending line appears to be:\n\n\n- name: 'Add epel repo'\n  ^ here\n"}
```

fix --check command

---

templates/backend.cfg

i suggest to add this **reqrep** feature to the backend template. 
As the official documentation says : 
> The legacy statements reqrep and reqirep are still usefull for the cases not yet covered by the http-request rules.
My use case is to remove the grafana web context, and no HTTP header fields can be change with a `http-request replace-value`. So, and it works, I need to add this line to the backend definition:
```
reqrep ^([^\ ]*\ /)grafana[/]?(.*) \1\2
```
Sources:
https://www.haproxy.com/doc/aloha/7.0/haproxy/http_rewriting.html#rewrite-anywhere-in-the-request-using-regexes
https://en.wikipedia.org/wiki/List_of_HTTP_header_fields

Add reqrep in the backend template.

---

templates/backend.cfg
templates/frontend.cfg
templates/listen.cfg
vars/main.yml

Adds missing request and response modification features to the backend template, bringing it to parity with the frontend one.
Breaking change for `reqrep` on backend: standardized to make this the same format as the frontend template - as in, it should be passed a list.

Add reqadd,rspadd,reqrep,reqirep,rsprep,rspirep to backend template

---

templates/listen.cfg
vars/main.yml

Adds the missing `maxconn` option to the listener template.

Add maxconn to listener template

---

README.md
defaults/main.yml
tasks/configure.yml
templates/resolvers.cfg
vars/main.yml

Adds the `haproxy_resolvers` variable for the use of [DNS Resolvers](https://cbonte.github.io/haproxy-dconv/1.6/configuration.html#5.3.2) in haproxy 1.6+, which permits runtime DNS resolution. Also added a task to clear the compiled folder, as renumbering of the sections was required to keep a sane compiled config order.

Add haproxy_resolvers configuration

---

templates/frontend.cfg

To use a named ACL in a monitor condition, it should be placed before the monitor definition

place acl rules in front of monitor rules
